### ISSUE TITLE
Is there a way to change the size of the hole in the middle that frames the client?

### ISSUE THREAD

**Issue by Elwaev** [piorrro33/overlay#16]
Basically title. I want to crop the view in a bit so the time remaining numbers aren't visible within the client itself.

**Comment by HarmfulBreeze** [comment]
Hi, I'm not sure I understand what you mean.
You may use "color key" in your streaming software to make the green rectangle at the center of the screen transparent, and put whatever you desire instead. If you choose to put the League Client in place of the rectangle, it's up to you to crop appropriately in your streaming software.
There's also a way to disable the champion previews when a player hovers a champion: in `config.conf`, set `championSplashesEnabled` to `false`.
You can also have an image instead of the green rectangle: put the image of your choice in `web/img/custom/stream_bg.png`.

Hope this helps!
