### ISSUE TITLE
Program doesn't work

### ISSUE THREAD

**Issue by logiclol** [piorrro33/overlay#24]
The program used to work without any issues for a long time but after not using it for a month, now the program doesn't work. Every time I try to run the "run.bat" it starts and shuts itself immediately in a second. I wasn't even able to read it. Then I took a video record and took a screenshot from it. Here's the error:
![screenshot](https://github.com/HarmfulBreeze/overlay/assets/53151242/5d0a0b06-12f8-41a4-9fbe-e5af8f4c0f0f)

I also tried to download the program from here from the zero but I still had the same issue.

I did change "nogui" to "true" before starting to see if maybe it would work, but it didn't change anything again.

I checked what is fasterxml jackson databind, I assume it's something with java but as I don't much have knowledge about coding, I don't know what to do about it. Am I missing an update or something?

Thanks for your time and help in advance.

**Comment by HarmfulBreeze** [comment]
Hi, thank you for your report.

Unfortunately this bug seems to be coming from the library that this project uses to connect to the Riot API, orianna. The library recently became outdated.
I think the library needs quite a bit of work to be updated to the latest changes to the API (but I might be wrong). Also, switching libraries would take quite a bit of time that I'm not willing to put into this.

I'm looking forward to an update to orianna, in the meantime there's not much I can do. If I have time I'll check whether simply updating the library to the latest snapshot would fix the issue you were facing.

Thanks :)
Pierre

**Comment by logiclol** [comment]
Thank you for your response, I appreciate the feedback.

I have been using your program for a couple of years and have created a lot of cool content with it. It's alright if you don't have time to fix the issue. 

Thank you so much for creating this program and letting us to use. I wish you a merry Christmas and happy new year to you and your loved ones <3

**Comment by HarmfulBreeze** [comment]
> Thank you for your response, I appreciate the feedback.
> 
> I have been using your program for a couple of years and have created a lot of cool content with it. It's alright if you don't have time to fix the issue.
> 
> Thank you so much for creating this program and letting us to use. I wish you a merry Christmas and happy new year to you and your loved ones <3

My heart is melting 😭 Thank you very much! Happy holidays to you as well!
